image: node:8

# Set up MySQL test-database
services:
  - mysql:5.5

# Configure test-database
variables:
  MYSQL_DATABASE: supertestdb
  MYSQL_ROOT_PASSWORD: secret


test-client:
  script:
    - npm install -g flow-bin
    - cd client
    - npm install
    - npm test
    - flow check src
  artifacts:
    paths:
      - client/coverage


test-server:
  script:
    - npm install -g flow-bin
    - cd daoServer
    - npm install
    - npm test
    - flow check src
  artifacts:
    paths:
      - daoServer/coverage

pages:
  stage: deploy
  dependencies:
    - test-server
    - test-client
  script:
    - mkdir .public
    - mkdir .public/client
    - mkdir .public/server
    - cp -r client/coverage/* .public/client
    - cp -r daoServer/coverage/* .public/server
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
