image: node:8

# Set up MySQL test-database
services:
  - mysql:5.5

# Configure test-database
variables:
  MYSQL_DATABASE: supertestdb
  MYSQL_ROOT_PASSWORD: secret


test:
  script:
    - npm install -g flow-bin
    - cd DaoServer && npm install && npm test && flow check src
    - cd ../Client && npm install && npm test && flow check src
